export default function Head() {
  return (
    <>
      <title>Desa Banjarejo | Official Website</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/logo/kab-mlg.svg" />
    </>
  );
}
